In [1]:
import numpy as np
import time


In [2]:
 arr = np.array([2,52,6,7])

In [3]:
print(arr,type(arr))

[ 2 52  6  7] <class 'numpy.ndarray'>


In [18]:
# fast calculation 
size = 100_000
py_list = list(range(size))
start_time = time.time()
sq_list = [i **2 for i in py_list]
end_time = time.time()
py_time = end_time - start_time
print(f"the time taken by py list is: {end_time - start_time}")
#  np calculation
np_arr = np.array(py_list)
start_time = time.time()
# vectorizition
sq_arr = np_arr **2
end_time = time.time()
np_time = end_time - start_time
print(f"the time taken by np list is: {end_time - start_time}")
time_difference = (py_time / np_time ) *100
print(time_difference)

the time taken by py list is: 0.006283283233642578
the time taken by np list is: 0.00045180320739746094
1390.7124010554091


In [17]:
# memory less taken + np is stored on contiguous memory location
import sys
py_size = sys.getsizeof(py_list) * len(py_list)
print(f"the size of the py list is: {py_size}")
np_size = np_arr.nbytes
print(f"the size of the np array is: {np_size}")
memory_diff = (py_size / np_size )*100
print(memory_diff)

the size of the py list is: 80005600000
the size of the np array is: 800000
10000700.0


In [25]:
# creating np array from lists
ar =np.array([3,6,6,1,6,2,7,9,"name"])
print(ar, type(ar))
print(ar.dtype)
print(ar.shape)
ar1 = np.array([[3,5,6,1] , [6,2,7,2] , [0,2,6,3]])
print(ar1)
print(type(ar1))
print(ar1.dtype)
print(ar1.shape)

['3' '6' '6' '1' '6' '2' '7' '9' 'name'] <class 'numpy.ndarray'>
<U21
(9,)
[[3 5 6 1]
 [6 2 7 2]
 [0 2 6 3]]
<class 'numpy.ndarray'>
int64
(3, 4)


In [45]:
# creating np arrays from scrtach

a1= np.zeros((3,3) , dtype = "int64")
print(a1, a1.shape)

a2= np.ones((3,3) , dtype = "int64")
print(a2, a2.shape)

a3= np.full((3,3) , 100 , dtype = "int64")
print(a3, a3.shape)

a4= np.eye((4) , dtype = "int64")
print(a4, a4.shape)

a5= np.arange(0,100)  
print(a5, a5.shape)

a6 = np.arange(0,20).reshape(4,5)
print(a6)

a7 = np.linspace(1,100,3)
print(a7)

[[0 0 0]
 [0 0 0]
 [0 0 0]] (3, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]] (3, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] (3, 3)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] (4, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99] (100,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[  1.   50.5 100. ]


In [48]:
# properties
b1 = np.array([[5,3,6],[7,7,2],[2,1,8]])
print(b1)
print(b1.dtype)
print(b1.shape)
print(b1.size)
print(b1.ndim)

b2 = b1.astype(np.float64)
print(b2)

[[5 3 6]
 [7 7 2]
 [2 1 8]]
int64
(3, 3)
9
2
[[5. 3. 6.]
 [7. 7. 2.]
 [2. 1. 8.]]


In [74]:
# Operations on Numpy
            # 1.Reshaping
b3 = np.array(list(range(1,21)))
print(b3, b3.dtype,b3.shape,b3.ndim)
# from flatten to matrix 2d
b4 = b3.reshape(5,4)
print(b4, b4.dtype,b4.shape,b4.ndim)

b5 = b4.flatten()
print(b5,b5.shape)

            # 2. Indexing

# Normal index
print(b4[1][2]) # 6
# for i in b4:
#     print(i)
# Fancy Indexing --- very easy b/c of vectorization  -- see it as whole rather than taversing 
f_index = [2,0,5]
print(b5[f_index])

# Boolean Indexing  --- basesd on condition true -- print or access the index
print(b5 [ b5 % 2 == 0 ])

            # 3. Slicing
print(b5[2:8]) # 3  4  5  6  7  8
print(b5[2:])
print(b5[:8])
print(b5[2:20:2])
print(b5[::-1])

#  copy VS view slicing in numpy is similar to list but big differenc in terms of interal works
# py list copy the list but in numpy array view is created which showing the original menas no agin creating like list
#  copy VS view

c_list =  [1,3,5,6,1,2]
print(c_list)
c_sub = c_list[0:4]
print(c_sub)
c_sub[1] = 300
print(c_sub)

print(f"agian the original : {c_list}")

c_np = np.array(c_list)
c_np_sub = c_np[0:4]   # .copy() this will not copy the entir but the copy of the slice view into the variable
print(c_np_sub)
c_np_sub [0] = 100
print("the updated sub: ",c_np_sub)
print("the updated origial np: ",c_np)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] int64 (20,) 1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]] int64 (5, 4) 2
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] (20,)
7
[3 1 6]
[ 2  4  6  8 10 12 14 16 18 20]
[3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5 6 7 8]
[ 3  5  7  9 11 13 15 17 19]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[1, 3, 5, 6, 1, 2]
[1, 3, 5, 6]
[1, 300, 5, 6]
agian the original : [1, 3, 5, 6, 1, 2]
[1 3 5 6]
the updated sub:  [100   3   5   6]
the updated origial np:  [1 3 5 6 1 2]


In [1]:
                # Numpy Common Data Types
'''
NumPy
Common Data Types

· Integers: int32, int64

. Floating point nums: float32, float64

· Boolean: boolb

. Complex nums: complex64, complex128

· String: S (byte-str) & U (unicode-str)

· Object: generic python objects - object
'''


'\nNumPy\nCommon Data Types\n\n· Integers: int32, int64\n\n. Floating point nums: float32, float64\n\n· Boolean: boolb\n\n. Complex nums: complex64, complex128\n\n· String: S (byte-str) & U (unicode-str)\n\n· Object: generic python objects - object\n'

In [3]:
import numpy as np

In [21]:
# Multi-dimensional arrays
arr2D = np.array([[3,6,2,6] ,[2,7,8,3],[2,6,2,7]])
print(arr2D,arr2D.dtype)
print(np.sum(arr2D))

sum_columns = np.sum(arr2D, axis = 0)
print(sum_columns)

sum_rows = np.sum(arr2D, axis= 1)
print(sum_rows)

# index slicing through axis
# accessing 7 8 
print(arr2D[1:3 , 1])

#      3D Array
arr3D = np.array([ [[1,2] , [3,4]] , [[5,6],[7,8]] ])
print(arr3D ,arr3D.shape)
print(f"accessing the 5 -- 1,0,0 the item is:  {arr3D[1,0,0]}")
#  index slicing through 3D
print(arr3D[ : , 0 , : ] )
 

[[3 6 2 6]
 [2 7 8 3]
 [2 6 2 7]] int64
54
[ 7 19 12 16]
[17 20 17]
[7 6]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
accessing the 5 -- 1,0,0 the item is:  5
[[1 2]
 [5 6]]


In [24]:
# broadcasting comapre from right to left. 1) should be equal 2) should be = to 1
ar1 = np.array([[3],[6],[8]])
ar2 = np.array([[2,4,9],
                [7,5,1],
               [1,2,4]])
sum1 = ar1 + ar2
print(sum1)


[[ 5  7 12]
 [13 11  7]
 [ 9 10 12]]


In [27]:
# vector Normalization
arr = np.array([[2,4,9],
                [7,5,1],
               [1,2,4]])
mean = np.mean(arr)
print(mean)
st_dev = np.std(arr)
print(st_dev)
normalize = (arr - mean)/st_dev
print(normalize)
print(np.sum(normalize))

3.888888888888889
2.6010444246043614
[[-0.72620401  0.04271788  1.96502261]
 [ 1.19610072  0.42717883 -1.11066496]
 [-1.11066496 -0.72620401  0.04271788]]
1.734723475976807e-16


In [39]:
# Q1
a = np.array([5, 10, 15, 20, 25])
print(a)

b = np.zeros([4,5])
print(b)
# c = np.eye([3])
# print(c)
d = np.array(list(range(51)))
print(d)
e = np.linspace(10,100,8)
print(e)

[ 5 10 15 20 25]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[ 10.          22.85714286  35.71428571  48.57142857  61.42857143
  74.28571429  87.14285714 100.        ]


In [46]:
a = np.arange(1,21)
print(a,a.size)
b = a.reshape([4,5])
print(b)
print(b.shape,b.ndim,b.size,b.dtype,b.itemsize)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 20
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5) 2 20 int64 8


In [55]:
a = np.arange(60)
print(a)
b = a.reshape([5,12])
print(b)
c = a.reshape([3,4,5])
print(c)
d = c.flatten()
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [65]:
arr = np.arange(1,26).reshape(5,5)
print(arr,arr.shape)
print(arr[3,2])
print(arr[4, : ])
print(arr[:, 1 ])
print(arr[1:4 , 1:4  ])
print(arr[: , 3:5 ])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] (5, 5)
18
[21 22 23 24 25]
[ 2  7 12 17 22]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [69]:
arr = np.arange(1,21)
print(arr[ arr % 2 ==0])
print(arr [ arr >=12 ])
idx = [0,3,7,10,15]
print( arr [ idx])

[ 2  4  6  8 10 12 14 16 18 20]
[12 13 14 15 16 17 18 19 20]
[ 1  4  8 11 16]


In [78]:
arr = np.arange(1,21)
print(arr, arr.dtype)
sub_view = arr[2:7]
print(sub_view)
(sub_cpy)= arr[1:8].copy()
print(sub_cpy)

sub_view[2] = 66
print(sub_view)
print(arr)
sub_cpy[0] = 33
print(sub_cpy)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] int64
[3 4 5 6 7]
[2 3 4 5 6 7 8]
[ 3  4 66  6  7]
[ 1  2  3  4 66  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[33  3  4  5  6  7  8]
[ 1  2  3  4 66  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [86]:
arr = np.array([
    [2,4,6],
    [1,3,5],
    [7,8,9]
])
print(arr.sum())
print(np.sum(arr))
print(np.sum(arr , axis = 1))
print(np.sum(arr , axis = 0))
print(np.mean(arr , axis = 1))
print(np.max(arr , axis = 0))

45
45
[12  9 24]
[10 15 20]
[4. 3. 8.]
[7 8 9]


In [91]:
a = np.arange(24).reshape(2,3,4)
print(a, a.shape,a.ndim)
print(a[0,:,:])
a[: , 0, :] = 99
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4) 3
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[99 99 99 99]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[99 99 99 99]
  [16 17 18 19]
  [20 21 22 23]]]


In [95]:
a = np.array([3,6,2,6,2,6,8,9,0] , dtype = "int64")
b = np.array([3,6,2,6,2,6,8,9,0] , dtype = "float64")
c = np.array([3,6,2,6,2,6,8,9,0] , dtype = "bool")
d = np.array([3,6,2,6,2,6,8,9,0] , dtype = "str")
print(a, a.dtype, b,b.dtype,c,c.dtype,d,d.dtype)
e = a.astype(dtype = "float64")
print(e,e.dtype)

[3 6 2 6 2 6 8 9 0] int64 [3. 6. 2. 6. 2. 6. 8. 9. 0.] float64 [ True  True  True  True  True  True  True  True False] bool ['3' '6' '2' '6' '2' '6' '8' '9' '0'] <U1
[3. 6. 2. 6. 2. 6. 8. 9. 0.] float64


In [103]:
a = np.array([3,6,2,6,2,6,8,9,0])
print(a)
print(a +10)
print(a *5)
b=np.array([100,200,300])
c = np.array([[1,2,3],
 [4,5,6]])
print(b+c)

[3 6 2 6 2 6 8 9 0]
[13 16 12 16 12 16 18 19 10]
[15 30 10 30 10 30 40 45  0]
[[101 202 303]
 [104 205 306]]


In [104]:
arr = np.array([
    [2,4,9],
    [7,5,1],
    [1,2,4]
])
nor = ( (arr - (arr.mean()) )) / arr.std()
print(nor)


[[-0.72620401  0.04271788  1.96502261]
 [ 1.19610072  0.42717883 -1.11066496]
 [-1.11066496 -0.72620401  0.04271788]]
